name: greghughes
favicon: null
layout_spectrum: 0.70802
typography_spectrum: 0.66126
title: greg hughes grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
